# Generated by Django 5.1.7 on 2025-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0002_remove_room_num_benches_room_floor_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='exam_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='subject_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
