# Generated by Django 5.2 on 2025-04-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0003_student_exam_date_student_exam_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam_type', models.CharField(choices=[('internal', 'Internal Exam'), ('semester', 'Semester Exam')], default='semester', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetables', to='exam_system.room')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('subject_code', 'date', 'start_time')},
            },
        ),
    ]
