# Generated by Django 5.1.7 on 2025-04-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='num_benches',
        ),
        migrations.AddField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_benches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
    ]
